login: &login
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>

test:
  <<: *login
  database: canvas_test

development:
  <<: *login
  database: canvas_test

production:
  <<: *login
  database: canvas
  queue:
    <<: *login
    database: canvas_queue
